import { constants, createCipheriv, createDecipheriv, publicEncrypt, randomBytes } from 'node:crypto';
import { LoxoneAuthenticationError, LoxoneProtocolError } from '../errors.js';

/**
 * Application-layer command encryption (AES-256-CBC + RSA key exchange).
 *
 * Required for Miniserver Generation 1 and for some token commands on non-TLS
 * connections; optional (but harmless) over WSS on new-generation hardware.
 *
 * Flow:
 *  1. A random AES-256 key and 16-byte IV are generated (constructor).
 *  2. `"{keyHex}:{ivHex}"` is RSA-encrypted with the Miniserver public key and
 *     sent via `jdev/sys/keyexchange/...` ({@link encryptSessionKey}).
 *  3. Each command is wrapped as `jdev/sys/enc/{uriEncode(AES("salt/{salt}/{cmd}"))}`
 *     ({@link encryptCommand}), rotating the salt periodically to defeat replay.
 */
export class CommandEncryption {
  private readonly key: Buffer;
  private readonly iv: Buffer;
  private salt: string;

  private saltUses = 0;
  private saltExpiresAt: number;
  private readonly maxSaltUses: number;
  private readonly maxSaltAgeMs: number;

  constructor(
    options: { saltBytes?: number; maxSaltUses?: number; maxSaltAgeMs?: number; key?: Buffer; iv?: Buffer } = {},
  ) {
    // The key/iv are randomly generated by default; they may be supplied for
    // deterministic/advanced scenarios (and testing).
    this.key = options.key ?? randomBytes(32);
    this.iv = options.iv ?? randomBytes(16);
    this.maxSaltUses = options.maxSaltUses ?? 20;
    this.maxSaltAgeMs = options.maxSaltAgeMs ?? 30_000;
    this.salt = generateSalt(options.saltBytes ?? 16);
    this.saltExpiresAt = Date.now() + this.maxSaltAgeMs;
  }

  /** RSA-encrypts the AES session key for the key-exchange command (base64). */
  encryptSessionKey(publicKeyPem: string): string {
    const payload = `${this.key.toString('hex')}:${this.iv.toString('hex')}`;
    try {
      const encrypted = publicEncrypt(
        { key: publicKeyPem, padding: constants.RSA_PKCS1_PADDING },
        Buffer.from(payload, 'utf8'),
      );
      return encrypted.toString('base64');
    } catch (cause) {
      throw new LoxoneAuthenticationError('Failed to RSA-encrypt the session key', { cause });
    }
  }

  /**
   * Wraps a plaintext command into an encrypted `jdev/sys/enc/...` command.
   * Rotates the salt with the `nextSalt/...` form when it expires.
   */
  encryptCommand(command: string): string {
    const plaintext = this.buildSaltedPlaintext(command);
    const cipher = this.aesEncrypt(plaintext);
    return `jdev/sys/enc/${encodeURIComponent(cipher)}`;
  }

  /**
   * Wraps a command requesting that the Miniserver also encrypt its response
   * (`jdev/sys/fenc/...`). Decrypt the response with {@link decryptResponse}.
   */
  encryptCommandWithEncryptedResponse(command: string): string {
    const cipher = this.aesEncrypt(this.buildSaltedPlaintext(command));
    return `jdev/sys/fenc/${encodeURIComponent(cipher)}`;
  }

  /** Decrypts a base64 AES response (from a `fenc` command) back to text. */
  decryptResponse(base64: string): string {
    try {
      const decipher = createDecipheriv('aes-256-cbc', this.key, this.iv);
      decipher.setAutoPadding(false);
      const out = Buffer.concat([decipher.update(Buffer.from(base64, 'base64')), decipher.final()]);
      // Strip zero padding and any leading "salt/.../" prefix echoed back.
      return out.toString('utf8').replace(/\0+$/, '');
    } catch (cause) {
      // A malformed/truncated ciphertext (e.g. length not a multiple of the block
      // size) makes the cipher throw a raw crypto error — surface it as a typed,
      // descriptive protocol error instead.
      throw new LoxoneProtocolError('Failed to decrypt an encrypted (fenc) response', { cause });
    }
  }

  private buildSaltedPlaintext(command: string): string {
    if (this.isSaltExpired()) {
      const previous = this.salt;
      this.salt = generateSalt(16);
      this.saltUses = 1;
      this.saltExpiresAt = Date.now() + this.maxSaltAgeMs;
      return `nextSalt/${previous}/${this.salt}/${command}`;
    }
    this.saltUses += 1;
    return `salt/${this.salt}/${command}`;
  }

  private isSaltExpired(): boolean {
    return this.saltUses >= this.maxSaltUses || Date.now() >= this.saltExpiresAt;
  }

  /**
   * AES-256-CBC encrypt with zero-byte padding, as the Miniserver expects.
   *
   * The Miniserver strips trailing zero bytes after decryption; PKCS#7 padding
   * (whose pad bytes are non-zero) would leak into the command it parses and into
   * the echoed response, so we pad manually with 0x00 and disable PKCS padding.
   */
  private aesEncrypt(plaintext: string): string {
    const cipher = createCipheriv('aes-256-cbc', this.key, this.iv);
    cipher.setAutoPadding(false);
    const data = Buffer.from(plaintext, 'utf8');
    const padLength = (16 - (data.length % 16)) % 16;
    const padded = padLength === 0 ? data : Buffer.concat([data, Buffer.alloc(padLength, 0)]);
    return Buffer.concat([cipher.update(padded), cipher.final()]).toString('base64');
  }
}

function generateSalt(bytes: number): string {
  // Salt is used inside a URL path segment, so percent-encode it.
  return encodeURIComponent(randomBytes(bytes).toString('hex'));
}
